### ISSUE TITLE
[Issue] DKCUI First Run Setup does not work if Python is not already installed.

### ISSUE THREAD

**Issue by RyanWalpole** [RWELabs/DKC-Toolbox#3]
### The Issue or Bug

When attempting to run DKCUI for the first time in Windows Sandbox, the application throws an unhandled exception.

### Version

DKCUI Version 0.01

### Operating System

Windows 11

### Steps to reproduce the behavior

1. Open a new Windows Sandbox environment
2. Run the installer for DKCUI
3. Complete the install and run DKCUI
4. Observe the first run setup
5. Issue is encountered, application throws unhandled exception

### Screenshots

![image](https://user-images.githubusercontent.com/69621127/222284457-88a91d75-57d3-4bf7-a706-d7009ba111dd.png)

### Additional Context

Full unhandled exception error message:
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Win32_CWI.NET_Application.Setup.InstallStepTwo_Tick(Object sender, EventArgs e) in C:\Users\rwalpole\Documents\GitHub\DKC-Toolbox\Project CWI\Win32 CWI .NET Application\Setup.cs:line 72
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9139.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
DKCUI
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RWE%20Labs/DKCUI/DKCUI.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9139.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9075.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
DotNetZip
    Assembly Version: 1.16.0.0
    Win32 Version: 1.16.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RWE%20Labs/DKCUI/DotNetZip.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9139.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

### Suggested Resolution

Requires triage and investigation.

**Comment by RyanWalpole** [comment]
**Issue Overview**
Issue seems to have occurred within a ``System.Diagnostics.Start(processInfo)`` event. There are several of these during the first run setup, however, this seems to be (from the screenshot) happening during the "Checking Python..." stage of the first run setup. There are two different events that could be related, however only one that fires without a prior message box:

1. The application runs a python.exe version check. It's possible that since Python is not installed, that the Sandbox doesn't handle the start process. In local testing however, it should just return a console error and not an unhandled exception. It is possible that the code is executing differently.

**Proposed Resolution**
The proposed resolution will be to add a ``try{}catch{}`` to catch the unhandled exception and assume it is an issue checking for the Python version - then moving on to a Python install. This seems like the most elegant and user friendly solution.

**Comment by RyanWalpole** [comment]
Associated issue #4 with Windows Sandbox / custom MS Store-less install. Otherwise issue is fixed.
